---
- name: fetch latest release manifest from github
  uri:
    url: https://api.github.com/repos/cli/cli/releases/latest
    return_content: true
  register: manifest_result
- name: download and install gh CLI
  become: true
  vars:
    jmes_query: "assets[?ends_with(name, 'amd64.deb')] | [0]"
    deb_asset: "{{ manifest_result.json | json_query(jmes_query) }}"
    src_prefix: "/usr/src"
  block:
    # TODO: Download signature as well, and verify
    - name: download package
      get_url:
        url: "{{ deb_asset.browser_download_url }}"
        dest: "{{ src_prefix }}/{{ deb_asset.name }}"
      register: download_result
    - name: install
      apt:
        deb: "{{ download_result.dest }}"
